# 4. Sync the compiled code securely to the IITI Server via Port 22
      - name: SFTP Deploy to CITC Infrastructure
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.IITI_HOST }}
          username: ${{ secrets.IITI_USERNAME }}
          password: ${{ secrets.IITI_PASSWORD }}
          port: 22 # Updated from 3004 to the working server port
          local-dir: ./
          server-dir: /home/iiti-stlab/htdocs/stlab.iiti.ac.in/ # Absolute target folder path
